### ISSUE TITLE
Send file extension while downloading/uploading it

### ISSUE THREAD

**Issue by lidaamber** [metarhia/server#27]
@tshemsedinov @belochub @nechaido  is it OK to send file extension while downloading/uploading files? It can be a return value in `downloadCode()` API method and can be sent to server as an argument in `endChatFileTransfer()` method, for example.

**Comment by belochub** [comment]
@lidaamber, may you please specify whether you are talking about chat file transfer or about file uploading/downloading with code (outside of chat)?

**Comment by lidaamber** [comment]
@belochub both of them

**Comment by tshemsedinov** [comment]
@metarhia/mobile @metarhia/jstp I think we need to change API for both to include file extension

**Comment by belochub** [comment]
@tshemsedinov, and what about this https://github.com/metarhia/Metarhia/issues/9#issuecomment-300917465:

> Files uploaded not in chat will be stored at hd and we will give user a code to download; no additional info, no filename or date/time, no even file type, absolute anonymity: no user;

Are we supposed to store original filename or file extension on server from now on?

**Comment by tshemsedinov** [comment]
@belochub I am not expert in mobile platforms, so I supposed that file type can be autodetected from the beginning but if we need to transmit it explicitly it is not an issue for anonymity.

**Comment by lidaamber** [comment]
@tshemsedinov it's needed to choose application to open downloaded file properly.

**Comment by nechaido** [comment]
@tshemsedinov @belochub's question was: "Should we store origial filename or not?"

**Comment by nechaido** [comment]
@lidaamber @tshemsedinov what about magic numbers, wouldn't it be better to use them instead?

**Comment by tshemsedinov** [comment]
@nechaido yes, we can encode ext in file codes (last letter, for example)

**Comment by lidaamber** [comment]
@nechaido I'm not against of magic numbers in such a way.

**Comment by nechaido** [comment]
@lidaamber what do you mean?

**Comment by nechaido** [comment]
@lidaamber @tshemsedinov so we do not need API change

**Comment by lidaamber** [comment]
@nechaido so will the file code format be changed?

**Comment by nechaido** [comment]
@lidaamber we do not need to, both java and swift  should provide tools for detecting file extension based on it's first bits.

**Comment by lidaamber** [comment]
@nechaido OK we can use such tools, but IMHO providing file type is easier.

**Comment by tshemsedinov** [comment]
@nechaido @lidaamber 
* we will not detect file type based on file first bytes (signature)
* on uploading server generates code and and we will put file type info into code
* we will not change contract and code format
* but we will add additional description how to generate code and how to get file type from code

I propose:
* use last letter to encode file type, G=gif, J=jpeg, P=png, S=svg, Z=zip, R=rar, 7=7zip, T=txt, D=pdf, H=html, A=avi, M=mp3, U=other/unknown
* When downloading all files marked with U will be saved as `*.dat`

**Comment by nechaido** [comment]
@tshemsedinov can I state that, due to our agreement earlier today, we will detect filetype based on first bits of file or first symbols of base64? It it is ok - please approve and close the issue.

**Comment by tshemsedinov** [comment]
@nechaido @lidaamber, we do not need multiple extensions and I believe that comparing first bytes with 10 signatires is not difficult gif, jpeg, png, svg, zip, rar, 7zip, pdf, mp3, avi. This solution is equal to extract file type from downloading code. So mobile implementation will be easy, not using third party complex libraries. In addition, it requires no changes in server implementation. So, it seems to me, that it will be best choice for us. What do you think?

**Comment by nechaido** [comment]
@tshemsedinov I suppose we should ask @GYFK and @GreatAndPowerfulKing about https://github.com/metarhia/server/issues/27#issuecomment-304396006 too.

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov If I understand you correctly we will extract file type from the beginning of `base64` string (e. g. "IVBOR…" means that it's `png`)?

And I'm not sure, that it's very good to restrict supporting file types list, because iOS (and Android as well, I think) can open any file if there is an appropriate app installed on the device.

**Comment by tshemsedinov** [comment]
We don't restrict file types, not listed types after downloading will be without extension or with `.dat` so user can choose an app to open it. @GreatAndPowerfulKing is it ok?

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov I don't know an app for iOS which may properly handle generic `.dat` file. So the only options for user will be to transmit file somewhere or to save it to iCloud Drive, but not open. In my opinion, it's ok. But it's up to you.

**Comment by tshemsedinov** [comment]
@GreatAndPowerfulKing maybe `notes` may store everything?

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov Yeah, store, but not open.

**Comment by GreatAndPowerfulKing** [comment]
Default system preview for files with unknown extension provides only such options (just sharing):
![img_1178](https://cloud.githubusercontent.com/assets/17301178/26520811/81d47206-42e2-11e7-8f69-7c0448609a02.PNG)
There is no possibility to view file content.

**Comment by tshemsedinov** [comment]
@GreatAndPowerfulKing that's ok as of now, for first version

**Comment by GreatAndPowerfulKing** [comment]
@tshemsedinov Okay. Will we support some other extensions in addition to ones you have specified earlier (gif, jpeg, png, svg, zip, rar, 7zip, pdf, mp3, avi)?

**Comment by nechaido** [comment]
@tshemsedinov @GreatAndPowerfulKing I agree with the idea we need to discuss this [topic](https://github.com/metarhia/server/issues/27#issuecomment-304446637), yet it is not the subject of this issue, so I propose to create a new one named:"Supported file types" and move the discussion there.

**Comment by nechaido** [comment]
Reopened due to https://github.com/metarhia/server/issues/28#issuecomment-306466129.
Although I don't like the idea to send redundant information over the network, I agree with @lidaamber to do so, if it is easier to implement necessary functionality this way.

**Comment by lidaamber** [comment]
@tshemsedinov ping

**Comment by tshemsedinov** [comment]
@belochub will detect extension on the server

**Comment by lidaamber** [comment]
@tshemsedinov ok
@nechaido @belochub could you update API, please?

**Comment by belochub** [comment]
Closed via https://github.com/metarhia/server/commit/06925882f1644af50efb3825f9525f28fb2e4758.
