### ISSUE TITLE
Supported file types

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/server#28]
As we discussed in #27 we will parse first bytes (signature) to detect file type, proposed by @nechaido 
I listed 10 types to support: gif, jpeg, png, svg, zip, rar, 7zip, pdf, mp3, avi.
@GreatAndPowerfulKing proposed to extend this list.
@metarhia/mobile feel free to extend the list.

**Comment by lidaamber** [comment]
@tshemsedinov I experimented with standard ways and various libs to get content type from incoming byte array. Unfortunately, all of them weren't good for type detection: some of them didn't support a lot of common file types, other detected them wrong etc. Could we send the file extension, please? After discussion with @nechaido we found out this solution as OK for both client and server.

**Comment by nechaido** [comment]
@lidaamber this comment is not related to the subject of this issue, any further conversations should take place at https://github.com/metarhia/server/issues/27#issuecomment-306496755.

**Comment by belochub** [comment]
The list of supported file types is now determined by the functionality of [this](https://www.npmjs.com/package/file-type) library.
